language: php

php:
  - 7.0
  - 7.1

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/phpunit --verbose
