language: php
sudo: false

jobs:
  include:
    - php: 7.0
      env: PHPUNIT_SUITE=All PHPSPEC=true
    - php: 7.1
      env: PHPUNIT_SUITE=Unit PHPSPEC=true
    - php: 7.2
      env: PHPUNIT_SUITE=Unit PHPSPEC=true
    - php: 7.3
      env: PHPUNIT_SUITE=Unit PHPSPEC=true
    - php: 7.4
      env: PHPUNIT_SUITE=All

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - ./phpspec.sh $PHPSPEC
  - vendor/bin/phpunit --verbose --testsuite $PHPUNIT_SUITE
